### ISSUE TITLE
Set AWS_DEFAULT_REGION

### ISSUE THREAD

**Issue by qoomon** [remind101/assume-role#28]
Set AWS_DEFAULT_REGION as well if set in profile config

**Comment by russellballestrini** [comment]
@qoomon would you like to try to tackle this PR?

**Comment by qoomon** [comment]
Unfortunately I'm not a go Developer however I figured out how you can get the Region out of a session.

**Comment by qoomon** [comment]
Eventually I get it working :-D #30

**Comment by qoomon** [comment]
And please update homebrew-formulae if you accept the pull request

**Comment by alexkoepke** [comment]
@qoomon were you ever able to get it working the homebrew was never updated.

**Comment by qoomon** [comment]
@alexkoepke actually I wrote my own CLI to tackle my needs see https://github.com/qoomon/aws-session

**Comment by alexkoepke** [comment]
Interesting I'll check it out.
