### ISSUE TITLE
Add the activated role to the terminal prompt to show which role is active

### ISSUE THREAD

**Issue by Vilsepi** [remind101/assume-role#36]
When working with multiple AWS accounts, setting default credentials with environment variables is potentially dangerous. The tool should (at least via an optional flag) add a visible notification to terminal prompt to remind use which role has been assumed.

For now, I have a wrapper for this: [assume-role-prompt](https://github.com/Vilsepi/assume-role-prompt).

**Comment by RichardBronosky** [comment]
This really isn't a function that the tool should perform. They define `${ASSUMED_ROLE}` and it is adequate for adding to the prompt. A wrapper like yours is exactly how this should be done. They tool shouldn't make assumptions about the user's prefered UX.

**Comment by russellballestrini** [comment]
@Vilsepi thank you for the link to your wrapper. I'm positive this will be useful to other people searching the issues for help!

For now I'm going to close as wont-fix - your wrapper is more of a solution than a work-around.

**Comment by russellballestrini** [comment]
@Vilsepi feel free to PR your wrapper into this repo under an examples directory.
