### ISSUE TITLE
Support for --duration-seconds

### ISSUE THREAD

**Issue by mthenw** [remind101/assume-role#6]
Hey @ejholmes,

thanks for a great tool. Would you accept PR adding support for `--duration-seconds` param?

**Comment by ejholmes** [comment]
@mthenw that'd be great!

**Comment by mthenw** [comment]
Any idea how this could look like as `assume-role` doesn't support named parameters? It's tricky because everything after `role` is treated as a command to exec.

**Comment by ejholmes** [comment]
Right now, it uses `os.Args` to grab the command and arguments to pass, but if you use the standard `flag` package, then [`flag.Args()`](https://golang.org/pkg/flag/#Args) returns all of the positional arguments after the flags, so we can do:

```console
$ assume-role --duration-seconds 60 <role>
```

**Comment by dlovitch** [comment]
Because of the new blog post announcing limits up to 12 hours, I get the sense that this feature could be even more useful: https://aws.amazon.com/blogs/security/enable-federated-api-access-to-your-aws-resources-for-up-to-12-hours-using-iam-roles/

**Comment by RichardBronosky** [comment]
Was this created before there was a `--duration` arg that accepts `12h`? If so, can this be closed?

**Comment by dlovitch** [comment]
I haven't used assume-role in a long while now, but it does seem like it based on https://github.com/remind101/assume-role/commit/7d9496a37a87e511267edd9cd86ec4384adbb58e which happened a couple of months after this issue was opened.

**Comment by russellballestrini** [comment]
Yeah, I'm going to close this as fixed. At somepoint the `--duration` flag was introduced so this feature request is solved.

@mthenw I'm assuming `--duration` in hours is a suitable solution to what you had in mind regarding `--duration-seconds`?
