### ISSUE TITLE
Parse roles out of ~/.aws/config

### ISSUE THREAD

**Issue by dgingrich** [remind101/assume-role#7]
`~/.aws/roles` duplicates the settings in `~/.aws/config`, which users will already have set if they use profiles with the AWS CLI (https://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html).  Can these be parsed directly out of `~/aws/config` instead of creating a new file?

**Comment by ejholmes** [comment]
Hey @dgingrich. This was built before the aws CLI supported roles in the config, but I think that sounds like a great idea! Pull requests welcome.

**Comment by dgingrich** [comment]
Thanks, I'll take a look at the code.  I assume you'd want to support both the `config` and the `roles` file so it doesn't break existing users who don't have their `config` file set up?

**Comment by ejholmes** [comment]
I we'd definitely want to support both. I think it would make sense to prefer `~/.aws/roles` if it's present (maybe even a warning on stderr), to give people a chance to move their role configurations over to `~/.aws/config`.

**Comment by dgingrich** [comment]
Resolved by https://github.com/remind101/assume-role/pull/11
