### ISSUE TITLE
Use AWS API instead of CLI

### ISSUE THREAD

**Issue by dgingrich** [remind101/assume-role#8]
Using the AWS go SDK (https://docs.aws.amazon.com/sdk-for-go/api/service/sts/) would make `assume-role` a self-contained binary instead of depending on the `aws` CLI.  Not urgent, the CLI is easy to installl; mostly interested if there's any reason why you prefer using the CLI instead of the SDK.

**Comment by ejholmes** [comment]
I swear I had a good reason for shelling out when I originally built this, but now I don't remember what the reason was. Anyways, hitting the STS API directly would definitely be better so that this can be self-contained. PR's welcome!
